apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: diskmaker-manager
  name: diskmaker-manager
  namespace: ${OBJECT_NAMESPACE}
spec:
  selector:
    matchLabels:
      app: diskmaker-manager
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: diskmaker-manager
    spec:
      containers:
      - args:
        - lv-manager
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: ${CONTAINER_IMAGE}
        imagePullPolicy: IfNotPresent
        name: diskmaker-manager
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /mnt/local-storage
          mountPropagation: HostToContainer
          name: local-disks
        - mountPath: /dev
          mountPropagation: HostToContainer
          name: device-dir
        - mountPath: /etc/provisioner/config
          name: provisioner-config
          readOnly: true
        - mountPath: /run/udev
          mountPropagation: HostToContainer
          name: run-udev
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      hostPID: true
      priorityClassName: ${PRIORITY_CLASS_NAME}
      serviceAccountName: local-storage-admin
      volumes:
      - hostPath:
          path: /mnt/local-storage
          type: ""
        name: local-disks
      - hostPath:
          path: /dev
          type: Directory
        name: device-dir
      - configMap:
          defaultMode: 420
          name: local-provisioner
        name: provisioner-config
      - hostPath:
          path: /run/udev
          type: ""
        name: run-udev
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 10%
    type: RollingUpdate
